# Dependencies


# Permalinks
permalink:        pretty

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content.'
url:              https://vidhyav656.github.io/
baseurl:          /

author:
  name:           'John Doe'
  url:            https://twitter.com/#

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
